rails_projects/omniauth-tutorial/config/routes.rb
OmniauthTutorial::Application.routes.draw do
  
  resources :sessions

  resources :frequencies
  root 'frequencies#index'
  
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy', as: 'signout'

end

rails_projects/omniauth-tutorial/app/models/frequency.rb
class Frequency < ActiveRecord::Base
end

rails_projects/omniauth-tutorial/app/models/session.rb
class Session < ActiveRecord::Base
end

rails_projects/omniauth-tutorial/app/models/user.rb
class User < ActiveRecord::Base
end

rails_projects/omniauth-tutorial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_projects/omniauth-tutorial/app/controllers/frequencies_controller.rb
class FrequenciesController < ApplicationController
  before_action :set_frequency, only: [:show, :edit, :update, :destroy]

  # GET /frequencies
  # GET /frequencies.json
  def index
    @frequencies = Frequency.all
  end

  # GET /frequencies/1
  # GET /frequencies/1.json
  def show
  end

  # GET /frequencies/new
  def new
    @frequency = Frequency.new
  end

  # GET /frequencies/1/edit
  def edit
  end

  # POST /frequencies
  # POST /frequencies.json
  def create
    @frequency = Frequency.new(frequency_params)

    respond_to do |format|
      if @frequency.save
        format.html { redirect_to @frequency, notice: 'Frequency was successfully created.' }
        format.json { render action: 'show', status: :created, location: @frequency }
      else
        format.html { render action: 'new' }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequencies/1
  # PATCH/PUT /frequencies/1.json
  def update
    respond_to do |format|
      if @frequency.update(frequency_params)
        format.html { redirect_to @frequency, notice: 'Frequency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequencies/1
  # DELETE /frequencies/1.json
  def destroy
    @frequency.destroy
    respond_to do |format|
      format.html { redirect_to frequencies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequency
      @frequency = Frequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frequency_params
      params[:frequency]
    end
end

rails_projects/omniauth-tutorial/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    #binding.py
    #used request.env rather than ev to enable controller testing
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

rails_projects/omniauth-tutorial/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_projects/omniauth-tutorial/app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

rails_projects/omniauth-tutorial/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails_projects/omniauth-tutorial/app/views/frequencies/_form.html.erb
<%= form_for(@frequency) do |f| %>
  <% if @frequency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frequency.errors.count, "error") %> prohibited this frequency from being saved:</h2>

      <ul>
      <% @frequency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_projects/omniauth-tutorial/app/views/frequencies/edit.html.erb
<h1>Editing frequency</h1>

<%= render 'form' %>

<%= link_to 'Show', @frequency %> |
<%= link_to 'Back', frequencies_path %>

rails_projects/omniauth-tutorial/app/views/frequencies/index.html.erb
<h1>Listing frequencies</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @frequencies.each do |frequency| %>
      <tr>
        <td><%= link_to 'Show', frequency %></td>
        <td><%= link_to 'Edit', edit_frequency_path(frequency) %></td>
        <td><%= link_to 'Destroy', frequency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frequency', new_frequency_path %>

rails_projects/omniauth-tutorial/app/views/frequencies/new.html.erb
<h1>New frequency</h1>

<%= render 'form' %>

<%= link_to 'Back', frequencies_path %>

rails_projects/omniauth-tutorial/app/views/frequencies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_frequency_path(@frequency) %> |
<%= link_to 'Back', frequencies_path %>

rails_projects/omniauth-tutorial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmniauthTutorial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>